version: 2.1
orbs:
  flutter: circleci/flutter@1.0.0
jobs:
  build-and-test:
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      - flutter/install
      - run:
          name: Get Flutter Dependencies
          command: flutter pub get

      - run:
          name: Build iOS Release
          command: |
            flutter build ios --release --no-codesign
workflows:
  version: 2
  build:
    jobs:
      - build-and-test
