version: 2.1

jobs:
  build:
    docker:
      # Specify the Docker image to use. This image includes Flutter.
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      # Restore cache (if available)
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pubspec.yaml" }}
            - v1-dependencies-
      # Get dependencies
      - run: flutter pub get
      # Save cache for future builds
      - save_cache:
          paths:
            - ~/.pub-cache
          key: v1-dependencies-{{ checksum "pubspec.yaml" }}
      # Run Flutter build
      - run: flutter build apk --release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

